include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true 
    prefer_single_quotes: true

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_use_of_visible_for_testing_member: ignore